### PR TITLE
Register range element into CoreModelModule

### LINKED ISSUE #245: DeserializationException with All_widgets.xml form
#### Software versions 
JavaRosa v2.7.0

#### Problem description
org.javarosa.core.util.externalizable.DeserializationException: No datatype registered to serialization code [d8 60 b9 d1]

#### Steps to reproduce the problem
Add a test to XFormParserTest:
```
@Test public void allWidgetsFormSavesAndRestores() throws IOException, DeserializationException {
    serAndDeserializeForm(r("All_widgets.xml"));
}
```
#### Expected behavior
Not the exception.
#### Other information 
I’m guessing there’s a class being serialized that isn’t registered with JavaRosa, and that it needs to be added here: https://github.com/opendatakit/javarosa/blob/15a825805a3f5976a908d0e8a1b65c7f8642cf96/src/org/javarosa/core/model/CoreModelModule.java#L26

[All_widgets.xml.txt](https://github.com/opendatakit/javarosa/files/1717676/All_widgets.xml.txt)

### PR DESCRIPTION
**Pull request by mdmahendri**
Closes #245 

#### What has been done to verify that this works as intended?
run unit test method provided by @dcbriccetti 

#### Why is this the best possible solution? Were any other approaches considered?
Insted of adding into `CoreModelModule` we can add `RangeQuestion` into another classes: `JavaRosaCoreModule` or `XFormsModule`, but only `CoreModelModule` seems relevant for me as `QuestionDef` is also placed there

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It should not, as mentioned in opendatakit/collect#2731 only throw warning

#### Do we need any specific form for testing your changes? If so, please attach one.
yes, i already added the form into `resources` dir. FYI i'm using the `all-widgets.xml` from collect assets not from the issue as it is latest version. Both forms passed the unit test

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No

### CODE REVIEW

File: test/org/javarosa/xform/parse/XFormParserTest.java [hunk 1]
```diff
@@ -202,6 +202,10 @@ private void timeParsing(LargeInstanceFileGenerator lfg, Path largeDataFilename,
         serAndDeserializeForm(r("Simpler_Cascading_Select_Form.xml"));
     }
 
+    @Test public void allWidgetsFormSavesAndRestores() throws IOException, DeserializationException {
```
Comment (ggalmazor) [inline test/org/javarosa/xform/parse/XFormParserTest.java]: I'm concerned that people reviewing this won't understand why this test is here and why it's important. Using all-widgets is a good idea, but here we need to make sure one can understand that this is a test that will prevent regression if the RangeWidget somehow disappears from the list of classes for JR serialization.

I'd suggest using a new form with just a range widget and adding a comment inside the test linking to the GitHub issue.

Comment (mdmahendri) [reply test/org/javarosa/xform/parse/XFormParserTest.java]: already done but we lose coverage on serialize/deserialize `OSMTag `, `GroupDef`,  and `SelectChoice` though. I squashed the commit, i assume this is okay?
Thanks for the review
