### PR TITLE
Pass through known bind attributes

### LINKED ISSUE #275: Required message ignored when jr:requiredMsg is set
#### Software versions 
JavaRosa v2.8.1 and 2.8.0

#### Problem description
`jr:requiredMsg` on bind is ignored.

It was originally reported here: https://github.com/opendatakit/collect/issues/2013

#### Steps to reproduce the problem
1. Load a form with a required message such as 
[required.xml.txt](https://github.com/opendatakit/javarosa/files/1811859/required.xml.txt)
2. Swipe forward on the first question

#### Expected behavior
A custom message should be shown.

#### Other information 
The problem is caused by https://github.com/opendatakit/javarosa/pull/238
Changes implemented in that pr caused that `rows` and `requiredMsg` attributes are completely ignored and they don't exist in additionalAttributes collection like before.

So not only `requiredMsg` is broken but `rows` too (we cant specify the number of rows for StringWidgets).

### PR DESCRIPTION
**Pull request by lognaturel**
Closes #275

#### What has been done to verify that this works as intended?
Automated test.

#### Why is this the best possible solution? Were any other approaches considered?
This makes it explicit why these attributes have special status and follows the original code structure. No changes are made to public interfaces. @grzesiek2010 has an alternative at grzesiek2010/javarosa@59ae8c5. I think that would also be ok but it buries the passed through attributes.

For `rows`, I don't think it's common/important enough to warrant invasive changes.

I removed a test that would never fail because it was checking for errors rather than warnings. Warnings go to the output stream so they can't easily be captured. I think that's ok.

#### Are there any risks to merging this code? If so, what are they?
This could further affect binding code or not actually fix the problem with `requiredMsg`.

### CODE REVIEW

**Comment by dcbriccetti** [comment]
I’ll probably finish reviewing later today, or, if you prefer to go ahead without me, please do.

**Comment by lognaturel** [comment]
Would be great to get your full review when you have a chance, @dcbriccetti!

File: src/org/javarosa/xform/parse/StandardBindAttributesProcessor.java [hunk 1]
```diff
@@ -116,11 +118,16 @@ DataBinding createBinding(IXFormParserFunctions parserFunctions, FormDef formDef
         binding.setPreload(element.getAttributeValue(NAMESPACE_JAVAROSA, "preload"));
         binding.setPreloadParams(element.getAttributeValue(NAMESPACE_JAVAROSA, "preloadParams"));
 
-        saveUnusedAttributes(binding, element, usedAttributes);
+        saveUnusedAttributes(binding, element, usedAttributes, passedThroughAttributes);
 
         return binding;
     }
 
+    DataBinding createBinding(IXFormParserFunctions parserFunctions, FormDef formDef,
```
Comment (dcbriccetti) [inline src/org/javarosa/xform/parse/StandardBindAttributesProcessor.java]: Is this method called? Everything still works when I delete it.

**Comment by dcbriccetti** [comment]
Since we’re letting rows result in a warning, perhaps we can fix the duplicate text in that message.
```
XForm Parse Warning: Warning: 1 Unrecognized attributes found in Element [input] and will be ignored: [rows] Location:
    Problem found at nodeset: /html/body/group[@appearance=field-list]/input
    With element <input ref="/data/meta/instanceID" rows="2"><label>
    Problem found at nodeset: /html/body/group[@appearance=field-list]/input
    With element <input ref="/data/meta/instanceID" rows="2"><label>
```
I recommend we delete this line 163 from unusedAttWarning in XFormUtils:
`warning+="Location:\n"+XFormParser.getVagueLocation(e);`

All callers of unusedAttWarning already display the “getVagueLocation”.

[unusedAttWarning.txt](https://github.com/opendatakit/javarosa/files/1823062/unusedAttWarning.txt)

With this change, the error message now looks like this:
```
XForm Parse Warning: Warning: 1 Unrecognized attributes found in Element [input] and will be ignored: [rows] 
     Problem found at nodeset: /html/body/group[@appearance=field-list]/input
     With element <input ref="/data/meta/instanceID" rows="2"><label>
```

File: src/org/javarosa/xform/parse/XFormParser.java [hunk 2]
```diff
@@ -1713,8 +1712,15 @@ protected DataBinding processStandardBindAttributes(List<String> usedAtts, Eleme
             "saveIncomplete"
     ));
 
+    // Attributes that are passed through to additionalAttrs but shouldn't lead to warnings.
```
Comment (dcbriccetti) [inline src/org/javarosa/xform/parse/XFormParser.java]: I’m a big fan of having comments like these be doc comments, so that I can press F1 on the identifier where it is referenced, and see a helpful display like this:

screen shot 2018-03-18 at 1 02 04 pm

File: src/org/javarosa/xform/parse/XFormParser.java [hunk 3]
```diff
@@ -869,11 +878,27 @@ else if (itemChildName.equals("value")) {
         return tags;
     }
 
-    protected QuestionDef parseControl(IFormElement parent, Element e, int controlType) {
-        return parseControl (parent, e, controlType, null);
+    private QuestionDef parseControl(IFormElement parent, Element e, int controlType) {
```
Comment (dcbriccetti) [inline src/org/javarosa/xform/parse/XFormParser.java]: Just making sure you’re aware that the return value from this method is never used. I would make the return type void, but I understand if you have a different preference.

File: src/org/javarosa/xform/parse/XFormParser.java [hunk 4]
```diff
@@ -869,11 +878,27 @@ else if (itemChildName.equals("value")) {
...
+        return parseControl (parent, e, controlType, null, null);
```
Comment (dcbriccetti) [inline src/org/javarosa/xform/parse/XFormParser.java]: Did you mean to have the space before the parenthesis? Same a few lines down.

File: src/org/javarosa/xform/parse/XFormParser.java [hunk 5]
```diff
@@ -869,11 +878,27 @@ else if (itemChildName.equals("value")) {
...
+     *
+     * @param parent                the form control element's parent
+     * @param e                     the form control element to parse
+     * @param controlType           one of the control types defined in {@link org.javarosa.core.model.Constants}
+     * @param additionalUsedAtts    attributes specific to the control type
+     * @param passedThroughAtts     attributes specific to the control type that should be passed through to
+     *                              additionalAttributes for historical reasons
+     * @return                      a {@link org.javarosa.core.model.QuestionDef} representing the form control element
+     */
+    private QuestionDef parseControl(IFormElement parent, Element e, int controlType, List<String> additionalUsedAtts,
```
Comment (dcbriccetti) [inline src/org/javarosa/xform/parse/XFormParser.java]: This doc comment is quite a nice improvement.

File: src/org/javarosa/xform/parse/XFormParser.java [hunk 6]
```diff
@@ -180,9 +180,16 @@ private static void initProcessingRules() {
...
+                    // Attributes that are passed through to additionalAttributes but shouldn't lead to warnings.
+                    // These are consistently used by clients but are expected in additionalAttributes for historical
+                    // reasons.
+                    final List<String> passedThroughInputAtts = Collections.unmodifiableList(Arrays.asList(
+                            "rows",
+                            "query"
+                    ));
+
+                    p.parseControl((IFormElement) parent, e, Constants.CONTROL_INPUT, passedThroughInputAtts,
+                            passedThroughInputAtts);
```
Comment (dcbriccetti) [inline src/org/javarosa/xform/parse/XFormParser.java]: Using `passedThroughInputAtts` for both `additionalUsedAtts` and `passedThroughAtts` bothers me a little. Am I too picky? For your consideration:

screen shot 2018-03-19 at 5 55 12 pm

File: src/org/javarosa/xform/parse/XFormParser.java [hunk 7]
```diff
@@ -1713,8 +1739,17 @@ protected DataBinding processStandardBindAttributes(List<String> usedAtts, Eleme
             "saveIncomplete"
     ));
 
-    protected void parseBind(Element element) {
-        final DataBinding binding = processStandardBindAttributes(usedAtts, element);
+    /**
+     * Attributes that are passed through to additionalAttrs but shouldn't lead to warnings.
+     * These are consistently used by clients but are expected in additionalAttrs for historical reasons.
+     **/
+    private final List<String> passedThroughAtts = Collections.unmodifiableList(Arrays.asList(
```
Comment (dcbriccetti) [inline src/org/javarosa/xform/parse/XFormParser.java]: This documenting is great!

**Comment by dcbriccetti** [comment]
Did you want to do this in a separate PR? (see above)

>delete this line 163 from unusedAttWarning in XFormUtils:
>warning+="Location:\n"+XFormParser.getVagueLocation(e);

Or just git-er-done here?

File: src/org/javarosa/xform/parse/XFormParser.java (hunk 3 above)
Comment (lognaturel) [reply src/org/javarosa/xform/parse/XFormParser.java]: Oh? I'm seeing it used in `parseUpload`.

File: src/org/javarosa/xform/parse/XFormParser.java (hunk 5 above)
Comment (lognaturel) [reply src/org/javarosa/xform/parse/XFormParser.java]: 🎉

File: src/org/javarosa/xform/parse/XFormParser.java (hunk 6 above)
Comment (dcbriccetti) [reply src/org/javarosa/xform/parse/XFormParser.java]: That’s fine.

File: src/org/javarosa/xform/parse/XFormParser.java (hunk 3 above)
Comment (dcbriccetti) [reply src/org/javarosa/xform/parse/XFormParser.java]: The second parseControl is called from parseUpload, no?

screen shot 2018-03-19 at 6 37 35 pm

**Comment by lognaturel** [comment]
@dcbriccetti if you are satisfied, you can merge. We'll do a QA pass when updating JR in Collect. 🙏
