### PR TITLE
bug #236: add attributes to appropriate whitelists

### LINKED ISSUE #236: Warning displayed when rows attribute is used on an input node.
#### Problem description
Warning displayed when `rows` attribute is used on an `input` node.

#### Steps to reproduce the problem
Add the `rows` attribute to a text field:
```
        <input ref="/data/comments" rows="2">
          <label>Comments</label>
        </input>
```
This is recognized and used by Collect and perhaps other clients but the following warning is shown using Validate:
```
Problem found at nodeset: 
    With element <input ref="/data/comments" rows="2"><label>
```

#### Expected behavior
No warning.

#### Other information 
I guess we should specifically allow `rows`. Another option would be to allow any attribute but that might be less helpful.

### PR DESCRIPTION
**Pull request by daveycrockett**
- `saveIncomplete` and `requiredMsg` added to allowed bind node attribs
- `rows` added to allowed input attributes

Closes #236 

#### What has been done to verify that this works as intended?
Added a unit test that parses an example form with the additional attributes

#### Why is this the best possible solution? Were any other approaches considered?
Follows existing conventions

#### Are there any risks to merging this code? If so, what are they?
None that I can see!

### CODE REVIEW

File: test/org/javarosa/xform/parse/XFormParserTest.java [hunk 1]
```diff
@@ -386,6 +386,11 @@ public void parseFormWithSetValueAction() throws IOException {
         assertThat(groupElement.getBind(), is(expectedXPathReference));
     }
 
+    @Test public void parseWithWhitelistedAttributes() throws IOException {
```
Comment (dcbriccetti) [inline test/org/javarosa/xform/parse/XFormParserTest.java]: When I created this class last April,

https://github.com/dcbriccetti/javarosa/commit/ab7517e984a34bedf82ddfe15507d7e4dc3381f2

I established a method naming convention based on the indicative mood (“parses…”, rather than “parse…”), in order to express what each method tests. I carried on like this for months until @mdudzinski joined in and started littering the code with imperative mood method names. :wink: I think he is not a native English speaker so he deserves some leeway. Now, @daveycrockett, you must choose which of us you wish to align with. :grin:

**Comment by daveycrockett** [comment]
Eek! I tend to follow "when in Rome," but this was subtle enough that I didn't notice the other method names! That's fixed (with a commit message also using the imperative aspect, just to be safe).

**Comment by lognaturel** [comment]
Thanks for doing this @daveycrockett!
